name: weather_mobx_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0
  weather_repository:
    path: ../../packages/weather_repository

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
