name: weather_simple_state_management_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  very_simple_state_manager: ^1.2.0+2
  weather_repository:
    path: ../../packages/weather_repository

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
