name: weather_riverpod_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  weather_repository:
    path: ../../packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
